config/routes.rb
# ChattyCrow types
resources :chatty_crow_channels, except: :show

app/models/chatty_crow_channel.rb
# encoding: utf-8
#
# This file is a part of Redmine ChattyCrow notifictation
#
# @author Strnadj <jan.strnadek@gmail.com>

# Usable channel in redmine
class ChattyCrowChannel < ActiveRecord::Base
  unloadable
  validates_presence_of :channel_type, :channel_token
  scope :active, lambda { where(active: true) }
  has_many :chatty_crow_user_settings, dependent: :delete_all
end

app/models/chatty_crow_user_setting.rb
# Model generated by scaffold
# Attributes
# user:references
# chatty_crow_channel:references
# contact:string

class ChattyCrowUserSetting < ActiveRecord::Base
  unloadable

  belongs_to :user
  belongs_to :chatty_crow_channel
  validates_presence_of :user, :chatty_crow_channel, :contact
end

app/controllers/chatty_crow_channels_controller.rb
# encoding: utf-8
#
# This file is a part of Redmine ChattyCrow notifictation
#
# @author Strnadj <jan.strnadek@gmail.com>

# Controler for managment chatty crow channels
class ChattyCrowChannelsController < ApplicationController
  unloadable

  before_filter :find_chatty_crow_channel, only: [:destroy, :edit, :update]
  before_filter :build_chatty_crow_channel_from_params, only: [:new, :create]

  # New channel
  # GET /new
  def new
  end

  # Create channel
  # POST /new
  def create
    if @chatty_crow_channel.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to_plugin_settings
    else
      render action: :new
    end
  end

  # Edit channel
  # GET /channel/:id/edit
  def edit
  end

  # Update channel
  # PUT /channel/:id
  def update
    if @chatty_crow_channel.update_attributes(params[:chatty_crow_channel])
      flash[:notice] = l(:notice_successful_create)
      redirect_to_plugin_settings
    else
      render action: :edit
    end
  end

  # Remove channel
  # DESTROY /channel/:id
  def destroy
    @chatty_crow_channel.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to_plugin_settings
  end

  private

  # Default redirect
  def redirect_to_plugin_settings
    redirect_to action: :plugin,
                controller: :settings,
                id: :redmine_chatty_crow_notifications,
                tab: :channels
  end

  def find_chatty_crow_channel
    @chatty_crow_channel = ChattyCrowChannel.find params[:id]
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def build_chatty_crow_channel_from_params
    if params[:chatty_crow_channel]
      @chatty_crow_channel = ChattyCrowChannel.new params[:chatty_crow_channel]
    else
      @chatty_crow_channel = ChattyCrowChannel.new
    end
  end
end

app/views/chatty_crow_channels/_form.html.erb
<%= error_messages_for 'chatty_crow_channel' %>

<div class="box tabular">
  <p>
    <%= f.select :channel_type, RedmineChattyCrowNotifications::SERVICES.sort.map { |m| [ m, m ] }, required: true %>
  </p>
  <p>
    <%= f.text_field :channel_token, required: true %>
  </p>
  <p>
    <%= f.check_box :active %>
  </p>
</div>

app/views/chatty_crow_channels/edit.html.erb
<h2><%= l(:label_chatty_crow_channel_edit) -%></h2>

<%= labelled_form_for @chatty_crow_channel do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/chatty_crow_channels/index.html.erb
<h2>ChattyCrowChannelsController#index</h2>

app/views/chatty_crow_channels/new.html.erb
<h2><%= l(:label_chatty_crow_channel_new) -%></h2>

<%= labelled_form_for @chatty_crow_channel do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= submit_tag l(:button_create) %>
<% end %>

app/views/settings/_chatty_crow.html.erb
<% chattycrow_tabs = [
      {
        name: 'general', partial: 'settings/chatty_crow_general', label: :label_chatty_crow_general
      },
      {
        name: 'channels', partial: 'settings/chatty_crow_channels', label: :label_chatty_crow_channel_plural
      }
   ]
%>

<%= render_tabs chattycrow_tabs %>

<% html_title(l(:label_settings), l(:chatty_crow_label_settings)) -%>

app/views/settings/_chatty_crow_channels.html.erb
<div class="contextual">
  <%= link_to l(:label_chatty_crow_channel_new), new_chatty_crow_channel_path, class: 'icon icon-add' %>
</div>

<h3><%= l(:label_chatty_crow_channel_plural) %></h3>

<table class="list">
  <thead>
    <tr>
      <th><%= l(:field_channel_type) %></th>
      <th><%= l(:field_channel_token) %></th>
      <th><%= l(:field_channel_active) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% for type in ChattyCrowChannel.order("channel_type ASC").all %>
      <tr class="<%= cycle("odd", "even") %>">
        <td><%= type.channel_type %></td>
        <td><%= type.channel_token %></td>
        <td align="center" style="width:15%;">
          <%= checked_image type.active? %>
        </td>
        <td class="buttons">
          <%= link_to l(:button_edit), edit_chatty_crow_channel_path(type), class: 'icon icon-edit' %>
          <%= link_to l(:button_delete), chatty_crow_channel_path(type), method: :delete, confirm: l(:text_are_you_sure), class: 'icon icon-del' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/settings/_chatty_crow_general.html.erb
<p>
  <label>
    <%= l(:label_chatty_crow_host) %> *
  </label>
  <%= text_field_tag 'settings[host]', @settings['host'], size: 50  %>
</p>

<p>
  <label>
    <%= l(:label_chatty_crow_application_token) %> *
  </label>
  <%= text_field_tag 'settings[token]', @settings['token'], size: 50  %>
</p>

<p>
  <label>
    <%= l(:label_chatty_crow_timeout) %> *
  </label>
  <%= text_field_tag 'settings[timeout]', @settings['timeout'], type: :number  %>
</p>

<% if defined?(::Sidekiq) %>
  <p>
    <label>
      <%= l(:label_chatty_crow_sidekiq) %> *
    </label>
    <%= check_box_tag 'settings[sidekiq]', 1, @settings['sidekiq'] == '1'  %>
  </p>
<% end %>